[build]
  command = "npm run build && npm run export"
  publish = "out"
[[plugins]]
package = "netlify-plugin-cache-nextjs"
    # These options will cache the build directory at `${NETLIFY_BASE}/frontend/.next-build`
    [plugins.inputs]
    # The path to the build directory
    build_dir_path = "frontend"